/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#0b1326',
        'on-background': '#dae2fd',
        'surface': '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'surface-tint': '#adc6ff',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'primary': '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'inverse-primary': '#005ac2',
        'secondary': '#b9c8de',
        'on-secondary': '#233143',
        'secondary-container': '#39485a',
        'on-secondary-container': '#a7b6cc',
        'secondary-fixed': '#d4e4fa',
        'secondary-fixed-dim': '#b9c8de',
        'on-secondary-fixed': '#0d1c2d',
        'on-secondary-fixed-variant': '#39485a',
        'tertiary': '#bcc7de',
        'on-tertiary': '#263143',
        'tertiary-container': '#8691a7',
        'on-tertiary-container': '#1f2a3c',
        'tertiary-fixed': '#d8e3fb',
        'tertiary-fixed-dim': '#bcc7de',
        'on-tertiary-fixed': '#111c2d',
        'on-tertiary-fixed-variant': '#3c475a',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '1.5rem',
        'section-gap': '4rem',
        'gutter': '2rem',
      },
      fontFamily: {
        'sans': ['Geist', 'sans-serif'],
        'mono': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.5', fontWeight: '500' }],
        'caption': ['13px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1100px',
      },
    },
    keyframes: {
      spotlight: {
        '0%': { opacity: 0, transform: 'translate(-72%, -62%) scale(0.5)' },
        '100%': { opacity: 1, transform: 'translate(-50%,-40%) scale(1)' },
      },
      'shimmer-slide': {
        to: { transform: 'translate(calc(100cqw - 100%), 0)' },
      },
      first: {
        '0%': { transform: 'translate(0%, 0%)' },
        '33%': { transform: 'translate(5%, -10%)' },
        '66%': { transform: 'translate(-5%, 5%)' },
        '100%': { transform: 'translate(0%, 0%)' },
      },
      second: {
        '0%': { transform: 'translate(0%, 0%)' },
        '33%': { transform: 'translate(-5%, 10%)' },
        '66%': { transform: 'translate(5%, -5%)' },
        '100%': { transform: 'translate(0%, 0%)' },
      },
      third: {
        '0%': { transform: 'translate(0%, 0%)' },
        '33%': { transform: 'translate(10%, 5%)' },
        '66%': { transform: 'translate(-10%, -5%)' },
        '100%': { transform: 'translate(0%, 0%)' },
      },
      fourth: {
        '0%': { transform: 'translate(0%, 0%)' },
        '33%': { transform: 'translate(-5%, -5%)' },
        '66%': { transform: 'translate(5%, 10%)' },
        '100%': { transform: 'translate(0%, 0%)' },
      },
      fifth: {
        '0%': { transform: 'translate(0%, 0%)' },
        '33%': { transform: 'translate(5%, 5%)' },
        '66%': { transform: 'translate(-5%, -10%)' },
        '100%': { transform: 'translate(0%, 0%)' },
      },
    },
    animation: {
      spotlight: 'spotlight 2s ease .75s 1 forwards',
      'shimmer-slide': 'shimmer-slide var(--speed) ease-in-out infinite alternate',
      first: 'first 8s ease infinite',
      second: 'second 10s ease infinite',
      third: 'third 12s ease infinite',
      fourth: 'fourth 9s ease infinite',
      fifth: 'fifth 11s ease infinite',
    },
  },
  plugins: [],
}
