'use client'

import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Sidebar from '@/components/Sidebar'
import TopBar from '@/components/TopBar'
import ReactMarkdown from 'react-markdown'

interface SectionDef {
  id: string
  icon: string
  iconBg: string
  iconText: string
  title: string
  subtitle: string
  query: string
}

export default function InsightsPage({ params }: { params: Promise<{ repo: string }> }) {
  const unwrappedParams = React.use(params)
  const repoId = unwrappedParams.repo
  const [expanded, setExpanded] = useState<string | null>(null)
  const [insights, setInsights] = useState<Record<string, string>>({})
  const [loadingSection, setLoadingSection] = useState<string | null>(null)

  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080'

  const sections: SectionDef[] = [
    {
      id: 'section-auth',
      icon: 'lock',
      iconBg: 'bg-primary/10 group-hover:bg-primary',
      iconText: 'text-primary group-hover:text-on-primary',
      title: 'Authentication',
      subtitle: 'Identity providers, JWT flow, and middleware',
      query: 'Explain the authentication flow, identity providers, and middleware used in this repository. Use markdown.',
    },
    {
      id: 'section-db',
      icon: 'storage',
      iconBg: 'bg-secondary-container/20 group-hover:bg-secondary',
      iconText: 'text-secondary group-hover:text-on-secondary',
      title: 'Database Schema',
      subtitle: 'ORM models, relationships, and migrations',
      query: 'Explain the database schema, ORM models, relationships, and any data architecture patterns found. Show schema code blocks if possible. Use markdown.',
    },
    {
      id: 'section-api',
      icon: 'api',
      iconBg: 'bg-tertiary-container/20 group-hover:bg-tertiary',
      iconText: 'text-tertiary group-hover:text-on-tertiary',
      title: 'API Endpoints',
      subtitle: 'REST resources and GraphQL resolution',
      query: 'List and describe the key API endpoints, REST resources, or GraphQL resolvers found in the repository. Use markdown.',
    },
    {
      id: 'section-env',
      icon: 'settings_input_component',
      iconBg: 'bg-surface-container-highest group-hover:bg-primary',
      iconText: 'text-outline group-hover:text-on-primary',
      title: 'Environment Variables',
      subtitle: 'Configuration, secrets, and staging flags',
      query: 'List the required environment variables, configuration flags, and secrets used in this repository based on .env files or config loaders. Use markdown.',
    },
    {
      id: 'section-queues',
      icon: 'queue',
      iconBg: 'bg-primary/10 group-hover:bg-primary',
      iconText: 'text-primary group-hover:text-on-primary',
      title: 'Queues & Workers',
      subtitle: 'Background workers, BullMQ, and cron tasks',
      query: 'Explain any background jobs, queues, workers, or cron tasks implemented in this repository. Use markdown.',
    },
  ]

  const toggle = async (section: SectionDef) => {
    if (expanded === section.id) {
      setExpanded(null)
      return
    }
    setExpanded(section.id)

    if (!insights[section.id]) {
      setLoadingSection(section.id)
      try {
        const res = await fetch(`${API_URL}/repositories/${repoId}/search`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ query: section.query }),
        })
        const data = await res.json()
        setInsights((prev) => ({ ...prev, [section.id]: data.answer || 'No insights found.' }))
      } catch (err) {
        setInsights((prev) => ({ ...prev, [section.id]: 'Failed to generate insights.' }))
      } finally {
        setLoadingSection(null)
      }
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <Sidebar activeItem="docs" />
      <TopBar activeNav="history" />

      <main className="ml-64 mt-16 px-8 py-8 flex justify-center">
        <div className="w-full max-w-[1100px]">
          {/* Header */}
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-10"
          >
            <div className="flex items-center gap-2 text-primary mb-2 text-sm font-medium">
              <span className="material-symbols-outlined text-[18px]">analytics</span>
              System Analysis
            </div>
            <h2 className="text-3xl font-bold text-on-surface mb-3">Extracted Information</h2>
            <p className="text-on-surface-variant max-w-2xl">
              Our AI audited your repository structure and logic flow. Expand each section for a granular deep-dive dynamically generated by Gemini!
            </p>
          </motion.section>

          {/* Accordion sections */}
          <div className="space-y-3 mb-12">
            {sections.map((section, i) => (
              <motion.div
                key={section.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.08 }}
                className="bg-surface-container-low/80 backdrop-blur-sm rounded-xl border border-outline-variant/40 overflow-hidden hover:border-primary/20 transition-colors"
              >
                <motion.button
                  className="w-full px-6 py-5 flex items-center justify-between group"
                  onClick={() => toggle(section)}
                  whileTap={{ scale: 0.998 }}
                >
                  <div className="flex items-center gap-4">
                    <div className={`w-11 h-11 rounded-xl flex items-center justify-center transition-all duration-300 ${section.iconBg} ${section.iconText}`}>
                      <span className="material-symbols-outlined text-[22px]" style={{ fontVariationSettings: "'FILL' 1" }}>{section.icon}</span>
                    </div>
                    <div className="text-left">
                      <h3 className="font-semibold text-on-surface">{section.title}</h3>
                      <p className="text-xs text-on-surface-variant">{section.subtitle}</p>
                    </div>
                  </div>
                  <motion.span
                    animate={{ rotate: expanded === section.id ? 180 : 0 }}
                    transition={{ duration: 0.25 }}
                    className="material-symbols-outlined text-outline"
                  >
                    expand_more
                  </motion.span>
                </motion.button>

                <AnimatePresence>
                  {expanded === section.id && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: [0.04, 0.62, 0.23, 0.98] }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 pb-6 pt-2 border-t border-outline-variant/30">
                        {loadingSection === section.id ? (
                          <div className="flex items-center gap-3 text-primary text-sm p-4">
                            <span className="material-symbols-outlined animate-spin">sync</span>
                            Generating AI insight...
                          </div>
                        ) : (
                          <div className="prose prose-invert prose-sm prose-primary max-w-none">
                            <ReactMarkdown>{insights[section.id]}</ReactMarkdown>
                          </div>
                        )}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}
